# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx

matrix:
  exclude:
  - os: osx
    r: devel

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars

r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'

cache: packages
sudo: false

warnings_are_errors: false
