# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

r_packages:
  - covr

warnings_are_errors: false  
  
after_success:
- Rscript -e 'covr::codecov()'
