## Col specifications for hap.py output

# Returns colspecs for import
#' @import readr
colspec <- function(tabletype = c("extended", "pr")) { # nocov start

  tabletype <- match.arg(tabletype)

  ## extended.csv
  if (tabletype == "extended") {
    colspec <- cols(
      Type = col_character(),
      Subtype = col_character(),
      Subset = col_character(),
      Filter = col_character(),
      Genotype = col_character(),
      QQ.Field = col_character(),
      QQ = col_character(),
      METRIC.Recall = col_double(),
      METRIC.Precision = col_double(),
      METRIC.Frac_NA = col_double(),
      METRIC.F1_Score = col_double(),
      FP.gt = col_integer(),
      FP.al = col_integer(),
      Subset.Size = col_double(),
      Subset.IS_CONF.Size = col_double(),
      Subset.Level = col_double(),
      TRUTH.TOTAL = col_integer(),
      TRUTH.TOTAL.ti = col_double(),
      TRUTH.TOTAL.tv = col_double(),
      TRUTH.TOTAL.het = col_double(),
      TRUTH.TOTAL.homalt = col_double(),
      TRUTH.TOTAL.TiTv_ratio = col_double(),
      TRUTH.TOTAL.het_hom_ratio = col_double(),
      TRUTH.TP = col_integer(),
      TRUTH.TP.ti = col_double(),
      TRUTH.TP.tv = col_double(),
      TRUTH.TP.het = col_double(),
      TRUTH.TP.homalt = col_double(),
      TRUTH.TP.TiTv_ratio = col_double(),
      TRUTH.TP.het_hom_ratio = col_double(),
      TRUTH.FN = col_integer(),
      TRUTH.FN.ti = col_double(),
      TRUTH.FN.tv = col_double(),
      TRUTH.FN.het = col_double(),
      TRUTH.FN.homalt = col_double(),
      TRUTH.FN.TiTv_ratio = col_double(),
      TRUTH.FN.het_hom_ratio = col_double(),
      QUERY.TOTAL = col_integer(),
      QUERY.TOTAL.ti = col_double(),
      QUERY.TOTAL.tv = col_double(),
      QUERY.TOTAL.het = col_double(),
      QUERY.TOTAL.homalt = col_double(),
      QUERY.TOTAL.TiTv_ratio = col_double(),
      QUERY.TOTAL.het_hom_ratio = col_double(),
      QUERY.TP = col_integer(),
      QUERY.TP.ti = col_double(),
      QUERY.TP.tv = col_double(),
      QUERY.TP.het = col_double(),
      QUERY.TP.homalt = col_double(),
      QUERY.TP.TiTv_ratio = col_double(),
      QUERY.TP.het_hom_ratio = col_double(),
      QUERY.FP = col_integer(),
      QUERY.FP.ti = col_double(),
      QUERY.FP.tv = col_double(),
      QUERY.FP.het = col_double(),
      QUERY.FP.homalt = col_double(),
      QUERY.FP.TiTv_ratio = col_double(),
      QUERY.FP.het_hom_ratio = col_double(),
      QUERY.UNK = col_integer(),
      QUERY.UNK.ti = col_double(),
      QUERY.UNK.tv = col_double(),
      QUERY.UNK.het = col_double(),
      QUERY.UNK.homalt = col_double(),
      QUERY.UNK.TiTv_ratio = col_double(),
      QUERY.UNK.het_hom_ratio = col_double()
    )
  }

  ## pr data
  if (tabletype == "pr") {
    colspec <- cols(
      Type = col_character(),
      Subtype = col_character(),
      Subset = col_character(),
      Filter = col_character(),
      Genotype = col_character(),
      QQ.Field = col_character(),
      QQ = col_double(),
      METRIC.Recall = col_double(),
      METRIC.Precision = col_double(),
      METRIC.Frac_NA = col_double(),
      METRIC.F1_Score = col_double(),
      FP.gt = col_integer(),
      FP.al = col_integer(),
      Subset.Size = col_integer(),
      Subset.IS_CONF.Size = col_double(),
      Subset.Level = col_double(),
      TRUTH.TOTAL = col_integer(),
      TRUTH.TOTAL.ti = col_character(),
      TRUTH.TOTAL.tv = col_character(),
      TRUTH.TOTAL.het = col_character(),
      TRUTH.TOTAL.homalt = col_character(),
      TRUTH.TOTAL.TiTv_ratio = col_character(),
      TRUTH.TOTAL.het_hom_ratio = col_character(),
      TRUTH.TP = col_integer(),
      TRUTH.TP.ti = col_character(),
      TRUTH.TP.tv = col_character(),
      TRUTH.TP.het = col_character(),
      TRUTH.TP.homalt = col_character(),
      TRUTH.TP.TiTv_ratio = col_character(),
      TRUTH.TP.het_hom_ratio = col_character(),
      TRUTH.FN = col_integer(),
      TRUTH.FN.ti = col_character(),
      TRUTH.FN.tv = col_character(),
      TRUTH.FN.het = col_character(),
      TRUTH.FN.homalt = col_character(),
      TRUTH.FN.TiTv_ratio = col_character(),
      TRUTH.FN.het_hom_ratio = col_character(),
      QUERY.TOTAL = col_integer(),
      QUERY.TOTAL.ti = col_character(),
      QUERY.TOTAL.tv = col_character(),
      QUERY.TOTAL.het = col_character(),
      QUERY.TOTAL.homalt = col_character(),
      QUERY.TOTAL.TiTv_ratio = col_character(),
      QUERY.TOTAL.het_hom_ratio = col_character(),
      QUERY.TP = col_integer(),
      QUERY.TP.ti = col_character(),
      QUERY.TP.tv = col_character(),
      QUERY.TP.het = col_character(),
      QUERY.TP.homalt = col_character(),
      QUERY.TP.TiTv_ratio = col_character(),
      QUERY.TP.het_hom_ratio = col_character(),
      QUERY.FP = col_integer(),
      QUERY.FP.ti = col_character(),
      QUERY.FP.tv = col_character(),
      QUERY.FP.het = col_character(),
      QUERY.FP.homalt = col_character(),
      QUERY.FP.TiTv_ratio = col_character(),
      QUERY.FP.het_hom_ratio = col_character(),
      QUERY.UNK = col_integer(),
      QUERY.UNK.ti = col_character(),
      QUERY.UNK.tv = col_character(),
      QUERY.UNK.het = col_character(),
      QUERY.UNK.homalt = col_character(),
      QUERY.UNK.TiTv_ratio = col_character(),
      QUERY.UNK.het_hom_ratio = col_character()
    )
  }

  colspec
} # nocov end
